# Generated by Django 3.0.7 on 2020-06-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('brands', '0001_initial'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_perform', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sales Perform %')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Desconto %')),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Purchase')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Marca')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Channel', verbose_name='Canal')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.Period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Simulator',
                'verbose_name_plural': 'Simulators',
            },
        ),
    ]
