# Generated by Django 3.0.7 on 2020-06-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assumptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receivable",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Contas à receber"
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Impostos"
                    ),
                ),
                (
                    "var_sales",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Variáveis de venda",
                    ),
                ),
                (
                    "other_suppliers",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Demais Fornecedores",
                    ),
                ),
                (
                    "cogs",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="CMV"
                    ),
                ),
                (
                    "tvc",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="CTV"
                    ),
                ),
                ("creation", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.Brand"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channel.Channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assumptions",
                "verbose_name_plural": "Assumptions",
            },
        ),
    ]
