# Generated by Django 3.0.7 on 2020-06-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('brands', '0001_initial'),
        ('assumptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Channel', verbose_name='Canal'),
        ),
    ]
