# Generated by Django 3.0.7 on 2020-06-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channel", "0001_initial"),
        ("brands", "0001_initial"),
        ("period", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_inventory",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Estoque inicial"
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Vendas"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Desconto %"
                    ),
                ),
                (
                    "purchase",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Purchase"
                    ),
                ),
                ("creation", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brands.Brand"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channel.Channel",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="period.Period"
                    ),
                ),
            ],
            options={"verbose_name": "Data", "verbose_name_plural": "Data",},
        ),
    ]
