# Generated by Django 3.0.7 on 2020-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("year_month", models.CharField(max_length=64)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"ordering": ("order",), "abstract": False,},
        ),
    ]
